version: '3.8'

services:
  mysqldb:
    container_name: mysql_db
    image: 'mysql:latest'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD_DEV}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DATABASE_NAME_DEV}
      MYSQL_USER: ${DATABASE_USER_DEV}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD_DEV}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - librooks
networks:
  librooks:
    driver: bridge

# COMMANDS: docker-compose up -d, docker-compose down
