name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check ESLint
        run: npm run lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
#  e2e-tests:
#    runs-on: ubuntu-latest
#    container:
#      image: node:18
#    services:
#      postgres-test:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: ${{secrets.DATABASE_USER_TEST}}
#          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD_TEST}}
#          POSTGRES_DB: ${{secrets.DATABASE_NAME_TEST}}
#        ports:
#          - 5432:5432
#        # Set health checks to wait until postgres has started
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#      redis-test:
#        image: redis:latest
#        ports:
#          - 6379:6379
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: Install dependencies
#        run: npm ci
#      - name: Run migrations
#        run: npm run db:migrate:test
#        env:
#          NODE_ENV: ${{secrets.NODE_ENV}}
#          PORT: ${{secrets.PORT}}
#          DATABASE_HOST_TEST: ${{secrets.DATABASE_HOST_TEST}}
#          DATABASE_PORT_TEST: ${{secrets.DATABASE_PORT_TEST}}
#          DATABASE_USER_TEST: ${{secrets.DATABASE_USER_TEST}}
#          DATABASE_PASSWORD_TEST: ${{secrets.DATABASE_PASSWORD_TEST}}
#          DATABASE_NAME_TEST: ${{secrets.DATABASE_NAME_TEST}}
#      - name: Run e2e tests
#        run: npm run test:e2e
#        env:
#          NODE_ENV: ${{secrets.NODE_ENV}}
#          PORT: ${{secrets.PORT}}
#          DATABASE_HOST_TEST: ${{secrets.DATABASE_HOST_TEST}}
#          DATABASE_PORT_TEST: ${{secrets.DATABASE_PORT_TEST}}
#          DATABASE_USER_TEST: ${{secrets.DATABASE_USER_TEST}}
#          DATABASE_PASSWORD_TEST: ${{secrets.DATABASE_PASSWORD_TEST}}
#          DATABASE_NAME_TEST: ${{secrets.DATABASE_NAME_TEST}}
#          EMAIL: ${{secrets.EMAIL}}
#          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
#          REDIS_HOST: ${{secrets.REDIS_HOST}}
#          REDIS_PORT: ${{secrets.REDIS_PORT}}
#          TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
#          TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
#          TWILIO_MESSAGING_SERVICE_SID: ${{secrets.TWILIO_MESSAGING_SERVICE_SID}}
#          TWILIO_WHATSAPP: ${{secrets.TWILIO_WHATSAPP}}
#          TOKEN_SECRET_KEY: ${{secrets.TOKEN_SECRET_KEY}}
#          SERVER_URL: ${{secrets.SERVER_URL}}
