name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master

jobs:
#  CI:
#    name: Continuos Integration
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: Setup Node.js 18.x
#        uses: actions/setup-node@v2
#        with:
#          node-version: 18.x
#          cache: "npm"
#      - name: Install dependencies
#        run: npm ci
#      - name: Make the environment file
#        uses: SpicyPizza/create-envfile@v1.3
#        with:
#          envkey_NODE_ENV: ${{secrets.NODE_ENV_PROD}}
#          envkey_PORT: ${{secrets.PORT}}
#          envkey_DATABASE_HOST_PROD: ${{secrets.DATABASE_HOST_PROD}}
#          envkey_DATABASE_PORT_PROD: ${{secrets.DATABASE_PORT_PROD}}
#          envkey_DATABASE_NAME_PROD: ${{secrets.DATABASE_NAME_PROD}}
#          envkey_DATABASE_USER_PROD: ${{secrets.DATABASE_USER_PROD}}
#          envkey_DATABASE_PASSWORD_PROD: ${{secrets.DATABASE_PASSWORD_PROD}}
#          envkey_DATABASE_ROOT_PASSWORD_PROD: ${{secrets.DATABASE_ROOT_PASSWORD_PROD}}
#          envkey_EMAIL: ${{secrets.EMAIL}}
#          envkey_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
#          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
#          envkey_ROOT_PASSWORD: ${{secrets.ROOT_PASSWORD}}
#          fail_on_empty: true
#      - name: Check ESLint
#        run: npm run lint
#      - name: Run migrations
#        run: npm run migration:run
#      - name: Run unit tests
#        run: npm run test:prod
#      - name: Run e2e tests
#        run: npm run test:e2e:prod
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    # needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_PROD }}
          username: ${{ secrets.AWS_USER_PROD }}
          key: ${{ secrets.AWS_SSH_KEY }}
          passphrase: ${{ secrets.AWS_SSH_PASSWORD }}
#          script: |
#            PATH=$PATH:/usr/bin &&
#            cd librooks &&
#            git pull origin master &&
#            npm install &&
#            npm run build &&
#            pm2 restart librooks
