name: Continuous Integration and Deployment

on:
  push:
    branches:
      - staging

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: node:18
    services:
      mysqldb-test:
        image: mysql:latest
        env:
          MYSQL_ROOT_HOST: ${{secrets.DATABASE_HOST_TEST}}
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_ROOT_PASSWORD_TEST}}
          MYSQL_DATABASE: ${{secrets.DATABASE_NAME_TEST}}
          MYSQL_USER: ${{secrets.DATABASE_USER_TEST}}
          MYSQL_PASSWORD: ${{secrets.DATABASE_PASSWORD_TEST}}
        ports:
          - 3306:3306
        # Set health checks to wait until mysql has started
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: ${{secrets.NODE_ENV_TEST}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_HOST_TEST: ${{secrets.DATABASE_HOST_TEST}}
          envkey_DATABASE_PORT_TEST: ${{secrets.DATABASE_PORT_TEST}}
          envkey_DATABASE_NAME_TEST: ${{secrets.DATABASE_NAME_TEST}}
          envkey_DATABASE_USER_TEST: ${{secrets.DATABASE_USER_TEST}}
          envkey_DATABASE_PASSWORD_TEST: ${{secrets.DATABASE_PASSWORD_TEST}}
          envkey_DATABASE_ROOT_PASSWORD_TEST: ${{secrets.DATABASE_ROOT_PASSWORD_TEST}}
          envkey_EMAIL: ${{secrets.EMAIL}}
          envkey_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_ROOT_PASSWORD: ${{secrets.ROOT_PASSWORD}}
          fail_on_empty: true
      - name: Check ESLint
        run: npm run lint
      - name: Run migrations
        run: npm run migration:run
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Write the steps here
